### ISSUE TITLE
Certificates not found when enabling SSL

### ISSUE THREAD

**Issue by ericksantillanp** [SAP/machine-learning-lab#8]
**Describe the issue:**

We are trying to deploy ml-lab with https enabled with a signed certificate from CA.
As stated on the [documentation](https://sap.github.io/machine-learning-lab/installation/install-lab/#configuration) we passed the `--env SERVICE_SSL_ENABLED=true` as well as we mount the volume with the certificates into /resources/ssl. .

When we run the container, we see on the logs, that the certificates were found:
```
Certificate for SSL/HTTPS was found in /resources/ssl
```

However when trying to connect to the access instance we get an error from chrome:
```
Your connection is not private
Attackers might be trying to steal your information from XXXXXXXXXXX (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID
```

And when checked the certificate used, it is a self-signed certificate and not the one that was under the mounted volume.

<img width="465" alt="Screenshot 2020-10-07 at 15 20 30" src="https://user-images.githubusercontent.com/69200659/95336266-c2c6b200-08b0-11eb-8890-d778e25745ca.png">

Furthermore, when checked with docker inspect the lab-backend container, it doesn't mount the folder.

After some debugging we found out two things:

1. The container that is spin-up in the beginning it's not the one that serves the back-end and UI latter. The "install container" spins-up other containers and then finishes. However, it seems that the volumes mounted are not passed to the "serve container". Clarifying this in the documentation could be helpful.
2. We see [here](https://github.com/SAP/machine-learning-lab/blob/b122530a5d2b977c14e8aed9b94c984cbf2628f9/backend/lab-service/src/main/java/org/mltooling/lab/services/managers/DockerServiceManager.java#L319) and [here](https://github.com/SAP/machine-learning-lab/blob/b122530a5d2b977c14e8aed9b94c984cbf2628f9/backend/lab-service/src/main/java/org/mltooling/lab/services/managers/DockerServiceManager.java#L38) that the serve container only expects the ssl certs to be on a named volume called lab-ssl and if this volume doesn't exist it seems that the service creates some self-signed certificates. The `-v /host/path/ssl:/resources/ssl:ro` doesn't have any influence on the deployment.

**Workaround**
A work around is to create a docker volume called lab-ssl where the cert.key and cert.crt can be found. The serve container will pick this volume automatically (no need to specify this on the deploy command line).

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): Linux
- Lab version : 
- Docker version : 19.03.13
- Command used to start the ML Lab :
The `cert.key` and `cert.crt` are under /host/path/ssl
```bash
docker run --rm \
           --env LAB_ACTION=install \
           --env LAB_PORT=443 \
           --env SERVICE_SSL_ENABLED=true \
           --env BACKEND_SERVICE_IMAGE=docker.pkg.github.com/sap/machine-learning-lab/lab-service:0.1.0 \
           --env MODEL_SERVICE_IMAGE=docker.pkg.github.com/sap/machine-learning-lab/lab-model-service:0.1.0 \
           --env WORKSPACE_IMAGE=docker.pkg.github.com/sap/machine-learning-lab/ml-workspace-lab:0.1.0 \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /host/path/ssl:/resources/ssl:ro \
           docker.pkg.github.com/sap/machine-learning-lab/lab-service:0.1.0
```
- Browser (Chrome/Firefox/Safari): Chrome

**Comment by raethlein** [comment]
Hey @ericksantillanp, you are right, the current documentation does not seem to be consistent with the code for ssl enablement. The certificates have to be placed in a named volume called 'lab-ssl' ([source code](https://github.com/SAP/machine-learning-lab/blob/e95d44edb479e0de0501cc5a0684c02c785dc31e/backend/lab-service/src/main/java/org/mltooling/lab/services/managers/DockerServiceManager.java#L314)). A host mounting, indeed, does not work.

In you case, you should be able to conveniently create and populate the named volume via following command: 
```
docker run \
  -v lab-ssl:/lab-ssl/ \
  -v /host/path/ssl/cert.crt:/ssl/cert.crt \
  -v /host/path/ssl/cert.key:/ssl/cert.key \
 ubuntu:20.04 cp -a /ssl/. /lab-ssl/
```

**Comment by ericksantillanp** [comment]
Hey @raethlein , thanks for the reply!
I'm not sure if this should be consider a lack of documentation or bug? Is it expected that the only way of enabling SSL is with a named volume called lab-ssl? Or should the user be able to use any volume with a `cert.crt` and `cert.key`  and mounted to /ressources/ssl ?

I would rather go the the latter one as it becomes rather difficult to perform this with docker-compose for example. As docker-compose always prefix the volumes and containers with `<FOLDER_NAME>_` and it becomes  impossible to create a volume call `lab-ssl` with it.

Here is an example of a docker-compose.yml:
```yaml
version: '3.2'
services:
    ml-lab:
        image: docker.pkg.github.com/sap/machine-learning-lab/lab-service:0.1.0
        volumes:
            # SSL certs
            - 'ssl:/certs'
            # docker socket
            - '/var/run/docker.sock:/var/run/docker.sock'
        environment: 
            - SERVICE_SSL_ENABLED=true
            - STUDIO_ACTION=install
            - STUDIO_PORT=30001
        depends_on: 
            - ubuntu
    # Container to populate the volume
    ubuntu:
        image: ubuntu:20.04
        volumes:
            - 'ssl:/ssl/'
            - '/host/path/ssl/cert.crt:/var/cert.crt'
            - '/host/path/ssl/cert.key:/var/cert.key'
        command: cp -a /var/. /ssl/

volumes:
    ssl:
```

I would propose that the installation container is able to pass the mount volumes to the serve container. What do you think?
